### PR TITLE
Use Response.StatusCode not .Status

### LINKED ISSUE #12: Bad HTTP status check
https://github.com/htcat/htcat/blob/master/http.go#L57 — Should check code, not phrase

### PR DESCRIPTION
**Pull request by tef**
Fixes #12

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
lgtm fix it @fdr fix it fix it!

**Comment by tef** [comment]
Also, how do we bundle this into transferatu ?

**Comment by uhoh-itsmaciek** [comment]
Or more generally, @fdr, what's the best way to build htcat for the platform?

**Comment by fdr** [comment]
"go build"?  There are no special requirements.  I used to use gobot when that existed.

**Comment by fdr** [comment]
@tt, @naaman, @ryanbrainard would know best

**Comment by fdr** [comment]
And @gudmundur.

**Comment by tt** [comment]
curl -O http://gobot-builder.herokuapp.com/build/github.com/htcat/htcat/cmd/htcat

**Comment by uhoh-itsmaciek** [comment]
I take back my lgtm. This is missing similar changes elsewhere: #14 is based on this and handles those as well.

**Comment by uhoh-itsmaciek** [comment]
@tt thanks, but gobot seems to have [bit rotted](https://github.com/kr/gobot/issues/2) and the current deployment is on go1.1--I think we'd like something more modern. I've built locally on my Ubuntu laptop for now.

**Comment by naaman** [comment]
[godist](https://godist.herokuapp.com/) sort of replaces gobot, but you're probably better off just setting up a travis job that uploads the binary to s3. Building locally is probably fine for anything but prod.

**Comment by uhoh-itsmaciek** [comment]
> This application will be able to read and write all public repo data. This includes the following:

Noping out of there. I don't see any docs in the [repo for godist](https://github.com/ddollar/godist), so not sure if there's a way to use it without that. But thanks.

This is for a vendored binary, so I'd love to avoid dealing with uploading to S3 as an intermediate step (since we'll just have to download right back to vendor it). I'll probably deal with one-off builds for now until I figure out either a Travis setup or get gobot working again.

**Comment by tt** [comment]
Closing in favor of #14.

**Pull request closed without merging**
